# Generated by Django 3.2.5 on 2021-07-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKlub', models.CharField(max_length=100)),
                ('presiden', models.CharField(max_length=100)),
                ('negaraKlub', models.CharField(max_length=100)),
                ('namaLiga', models.CharField(max_length=100)),
                ('tahunBerdiri', models.IntegerField()),
                ('logo', models.URLField()),
            ],
            options={
                'ordering': ['-tahunBerdiri'],
            },
        ),
        migrations.CreateModel(
            name='PemainBola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('noPunggung', models.IntegerField()),
                ('asalNegara', models.CharField(max_length=100)),
                ('umur', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('gambar', models.URLField()),
                ('asalKlub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klub', to='DjangoAPIapp.klub')),
            ],
            options={
                'ordering': ['-role'],
            },
        ),
    ]
