# Generated by Django 3.2.5 on 2021-07-08 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPIapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klub',
            options={'ordering': ['-data_created']},
        ),
        migrations.AlterModelOptions(
            name='pemainbola',
            options={'ordering': ['-data_created']},
        ),
        migrations.AddField(
            model_name='klub',
            name='data_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pemainbola',
            name='data_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
