# Generated by Django 3.2.5 on 2021-07-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DjangoAPIapp', '0002_auto_20210708_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemainbola',
            name='asalKlub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemainbola', to='DjangoAPIapp.klub'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('klub', models.ManyToManyField(to='DjangoAPIapp.Klub')),
                ('pemainbola', models.ManyToManyField(to='DjangoAPIapp.PemainBola')),
            ],
            options={
                'ordering': ['favorite_id', '-created_at'],
            },
        ),
    ]
